# syntax=docker/dockerfile:1
ARG BASE_DIGEST=4f71d532a25f8f0690ac6bf37616a3b2fc051d5535f3e32489fe8a62093b931d
FROM debian@sha256:${BASE_DIGEST}

ARG LOGSTASH_PORT
ARG LOGSTASH_VERSION
ARG LOGSTASH_SCRIPT
ARG CURL_VERSION=7.74.0-1.3+deb11u14
ARG JAVA_VERSION=17.0.15+6-1~deb11u1

RUN apt-get update && \
	apt-get install -y openjdk-17-jdk=${JAVA_VERSION} curl=${CURL_VERSION} gosu

COPY --chmod=744 ${LOGSTASH_SCRIPT}logstash_entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
EXPOSE ${LOGSTASH_PORT}
CMD ["./logstash"]
