services:
  nginx:
    build: 
      context: 
        ${NGINX_PATH}
      args:
        BASE_IMAGE:   ${BASE_IMAGE}
        BASE_DIGEST:  ${BASE_DIGEST}
        NGINX_PORT:   ${NGINX_PORT}
    ports:
      - "${NGINX_PORT}:80"
    expose:
      - "${NGINX_PORT}"
      - "9000"    
#volumes:
#depends_on:
