networks:
  app-network: {}

services:
  nginx:
    container_name: nginx
    build: 
      context: 
        ${NGINX_PATH}
      args:
        BASE_DIGEST:        ${BASE_DIGEST}
        NGINX_PORT:         ${NGINX_PORT}
        NGINX_SCRIPT:       ${SCRIPTS}
        NGINX_VERSION:      ${NGINX_VERSION}
    environment:
      - NGINX_PORT
      - DOMAIN_NAME
      - NGINX_BDIR
      - SSL_CERT
      - SSL_CERT_KEY
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ${WP_VOLUME}:/var/www/html
    networks:
      - ${NETWORK}
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build:
      context:
        ${MARIADB_PATH}
      args:
        BASE_DIGEST:      ${BASE_DIGEST}
        MARIADB_PORT:     ${MARIADB_PORT}
        MARIADB_SCRIPT:   ${SCRIPTS}
        MARIADB_VERSION:  ${MARIADB_VERSION}
    environment:
      - MYSQL_USER
      - MYSQL_USER_PASSWORD
      - MYSQL_ROOT
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MARIADB_PORT
      - MYSQL_DATADIR
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    volumes:
      - ${MDB_VOLUME}:/var/lib/mysql
    networks:
      - ${NETWORK}
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context:
        ${WORDPRESS_PATH}
      args:
        BASE_DIGEST:      ${BASE_DIGEST}
        WORDPRESS_PORT:   ${WORDPRESS_PORT}
        WORDPRESS_SCRIPT: ${SCRIPTS}
    ports:
      - "${WORDPRESS_PORT}:${WORDPRESS_PORT}"
    volumes:
      - ${WP_VOLUME}:/var/www/html
    networks:
      - ${NETWORK}
    restart: unless-stopped

#CMD ["sh", "-c", "while true; do sleep 60; done"]
