services:
  nginx:
    build: 
      context: 
        ${NGINX_PATH}
      args:
        BASE_IMAGE:         ${BASE_IMAGE}
        BASE_DIGEST:        ${BASE_DIGEST}
        NGINX_PORT:         ${NGINX_PORT}
        NGINX_SCRIPT:       ${SCRIPTS}
        NGINX_CONF:         ${CONF}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ${DWP_VOLUME}:/var/www/html
    restart: unless-stopped

  mariadb:
    build:
      context:
        ${MARIADB_PATH}
      args:
        BASE_IMAGE:     ${BASE_IMAGE}
        BASE_DIGEST:    ${BASE_DIGEST}
        MARIADB_PORT:   ${MARIADB_PORT}
        MARIADB_SCRIPT: ${SCRIPTS}
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    volumes:
      - ${DMDB_VOLUME}:/var/www/html
    restart: unless-stopped
