services:
  nginx:
    container_name: nginx
    build: 
      context: 
        ${NGINX_PATH}
      args:
        BASE_DIGEST:        ${BASE_DIGEST}
        NGINX_PORT:         ${NGINX_PORT}
        NGINX_SCRIPT:       ${SCRIPTS}
        NGINX_CONF:         ${CONF}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ${WP_VOLUME}:/var/www/html
    networks:
      - ${NETWORK}
    healthcheck:
      test: ["CMD", "${SCRIPTS}check.sh"]
      interval: 30s
      retries: 3
    restart: unless-stopped

  mariadb:
      container_name: mariadb
      build:
        context:
          ${MARIADB_PATH}
        args:
          BASE_DIGEST: ${BASE_DIGEST}
          MARIADB_PORT: ${MARIADB_PORT}
          MARIADB_SCRIPT: ${SCRIPTS}
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: mydb
      ports:
        - "${MARIADB_PORT}:${MARIADB_PORT}"
      volumes:
        - ${MDB_VOLUME}:/var/www/html
      networks:
        - ${NETWORK}
      restart: unless-stopped

  # wordpress:
  #   container_name: wordpress
  #   build:
  #     context:
  #       ${WORDPRESS_PATH}
  #     args:
  #       BASE_DIGEST: ${BASE_DIGEST}
  #       WORDPRESS_PORT: ${WORDPRESS_PORT}
  #     ports:
  #       - "${WORDPRESS_PORT}:${WORDPRESS_PORT}"
  #     volumes:
  #       - ${WP_VOLUME}:/var/www/html
  #     networks:
  #       - ${NETWORK}
  #     depends_on:
  #         nginx:
  #           condition: service_healthy
  #     restart: unless-stopped

networks:
  app-network:
    driver: bridge
