networks:
  app-network: {}

secrets:
  db_password:
    file: ${SECRETS}/db_user_password.txt
  db_root_password:
    file: ${SECRETS}/db_root_password.txt
  
services:
  nginx:
    container_name: nginx
    build: 
      context: 
        ${NGINX_PATH}
      args:
        BASE_DIGEST:        ${BASE_DIGEST}
        NGINX_PORT:         ${NGINX_PORT}
        NGINX_SCRIPT:       ${SCRIPTS}
        NGINX_VERSION:      ${NGINX_VERSION}
    environment:
      - NGINX_PORT
      - DOMAIN_NAME
      - NGINX_BDIR
      - SSL_PATH
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ${WP_VOLUME}:/var/www/html
    networks:
      - ${NETWORK}
    restart: unless-stopped
  
  vsftpd:
    container_name: vsftpd
    build:
      context:
        ${VSFTPD_PATH}
      args:
        BASE_DIGEST:      ${BASE_DIGEST}
        VSFTPD_PORT:      ${VSFTPD_PORT}
        VSFTPD_SCRIPT:    ${SCRIPTS}
        VSFTPD_VERSION:   ${VSFTPD_VERSION}
    environment:
      - VSFTPD_VERSION
    ports:
      - "${VSFTPD_PORT}:${VSFTPD_PORT}"
    #expose:
     # - "${VSFTPD_PORT}"
    volumes:
      - ${WP_VOLUME}:/var/www/html
    networks:
      - ${NETWORK}
    restart: unless-stopped

  adminer:
    container_name: adminer
    build:
      context:
        ${ADMINER_PATH}
      args:
        BASE_DIGEST:      ${BASE_DIGEST}
        ADMINER_PORT:     ${ADMINER_PORT}
        ADMINER_SCRIPT:   ${SCRIPTS}
        ADMINER_VERSION:  ${ADMINER_VERSION}
        PHP_VERSION:      ${PHP_VERSION}
    environment:
      - ADMINER_VERSION
      - PHP_VERSION
    expose:
      - "${ADMINER_PORT}"
    volumes:
      - ${WP_VOLUME}:/var/www/html
    networks:
      - ${NETWORK}
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context:
        ${WORDPRESS_PATH}
      args:
        BASE_DIGEST:      ${BASE_DIGEST}
        WP_PORT:          ${WORDPRESS_PORT}
        WP_SCRIPT:        ${SCRIPTS}
        WP_CONF:          ${CONF}
        WP_VERSION:       ${WP_VERSION}
        PHP_VERSION:      ${PHP_VERSION}
    secrets:
      - db_password
    environment:
      - WP_DB=${MYSQL_DATABASE}
      - WP_DB_USER=${MYSQL_USER}
      - WP_DB_PASSWORD_FILE=/run/secrets/db_password
      - WP_HOST
      - WP_CHARSET
      - WP_PREFIX
      - WP_DEBUG
      - WP_VERSION
      - PHP_VERSION
    expose:
      - "${WORDPRESS_PORT}"
    volumes:
      - ${WP_VOLUME}:/var/www/html
    networks:
      - ${NETWORK}
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build:
      context:
        ${MARIADB_PATH}
      args:
        BASE_DIGEST:      ${BASE_DIGEST}
        MARIADB_PORT:     ${MARIADB_PORT}
        MARIADB_SCRIPT:   ${SCRIPTS}
        MARIADB_VERSION:  ${MARIADB_VERSION}
    secrets:
      - db_password
      - db_root_password
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_USER_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_PORT
      - MYSQL_DATADIR
    expose:
      - "${MARIADB_PORT}"
    volumes:
      - ${MDB_VOLUME}:/var/lib/mysql
    networks:
      - ${NETWORK}
    restart: unless-stopped
