# syntax=docker/dockerfile:1
ARG BASE_DIGEST
FROM alpine@sha256:${BASE_DIGEST}

ARG MARIADB_PORT
ARG MARIADB_SCRIPT

RUN 	apk update && \
	apk add --no-cache mariadb su-exec gettext && \
	mkdir -p /run/mysqld /var/lib/mysql && \
    	chown -R mysql:mysql /run/mysqld /var/lib/mysql && \
	mysql_install_db --user=mysql --datadir=/var/lib/mysql

COPY 	--chmod=444 ${MARIADB_SCRIPT}mdb.cnf.template /
COPY 	--chmod=755 ${MARIADB_SCRIPT}mdb_entrypoint.sh /entrypoint.sh

EXPOSE ${MARIADB_PORT}
ENTRYPOINT ["/entrypoint.sh"]
CMD ["mysqld"]
