# syntax=docker/dockerfile:1
ARG BASE_DIGEST
FROM alpine@sha256:${BASE_DIGEST}

ARG MARIADB_VERSION
ARG MARIADB_PORT
ARG MARIADB_SCRIPT
ARG SEXEC_VERSION=0.2-r3

RUN 	apk update && \
	apk add --no-cache mariadb=${MARIADB_VERSION} \
		su-exec=${SEXEC_VERSION} \ 
		mariadb-client=${MARIADB_VERSION}

RUN	mkdir -p /run/mysqld /var/lib/mysql && \
	chown -R mysql:mysql /var/lib/mysql /run/mysqld

COPY 	--chmod=755 ${MARIADB_SCRIPT}mdb_entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
EXPOSE ${MARIADB_PORT}
CMD ["mysqld"]
