FROM debian:bullseye


RUN apt update -y

RUN apt install vsftpd -y
RUN apt install gettext -y

#COPY --chmod=744 ./tools/script.sh /
COPY --chmod=744 ./tools/vsftpd.cnf.template /
COPY --chmod=744 ./tools/vsftpd_entrypoint.sh /script.sh

CMD ["/script.sh"]
