# syntax=docker/dockerfile:1
ARG BASE_DIGEST
FROM alpine@sha256:${BASE_DIGEST}

ARG WORDPRESS_PORT
ARG WP_VERSION
ARG PHP_VERSION=php82
ARG CURL_VERSION=8.12.1-r0
ARG GTXT_VERSION=0.22.5-r0

RUN	apk update && \
	apk add --no-cache curl=${CURL_VERSION} ${PHP_VERSION} ${PHP_VERSION}-fpm gettext=${GTXT_VERSION} && \
	mkdir -p /usr/share/webapps/ && \
	cd /usr/share/webapps/ && \
	curl -O https://wordpress.org/wordpress-${WP_VERSION}.tar.gz && \
	tar -xzvf wordpress-${WP_VERSION}.tar.gz && \
	rm wordpress-${WP_VERSION}.tar.gz

EXPOSE ${WORDPRESS_PORT}
CMD ["sh", "-c", "while true; do sleep 60; done"]
