# syntax=docker/dockerfile:1
ARG BASE_IMAGE
ARG BASE_DIGEST
FROM ${BASE_IMAGE}@sha256:${BASE_DIGEST}

ARG NGINX_PORT
EXPOSE ${NGINX_PORT}

COPY ./conf/nginx.conf /etc/nginx/

RUN 	apk update && \
	apk add --no-cache nginx && \
	mkdir -p /usr/share/nginx/html && \  
	echo "<html><body><h1>Hola, Nginx esta funcionando!</h1></body></html>" > /usr/share/nginx/html/index.html

CMD ["nginx", "-g", "daemon off;"]
